//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MissionManagement
{
    public class MFloatArray : Message
    {
        public const string RosMessageName = "mission_management/FloatArray";

        //  Since ROS doesn't support 2D arrays this message provides
        //  a workaround since it can be put into a list and create a
        //  2 dimensional vector with it
        public double[] col;

        public MFloatArray()
        {
            this.col = new double[0];
        }

        public MFloatArray(double[] col)
        {
            this.col = col;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            
            listOfSerializations.Add(BitConverter.GetBytes(col.Length));
            foreach(var entry in col)
                listOfSerializations.Add(BitConverter.GetBytes(entry));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            
            var colArrayLength = DeserializeLength(data, offset);
            offset += 4;
            this.col= new double[colArrayLength];
            for(var i = 0; i < colArrayLength; i++)
            {
                this.col[i] = BitConverter.ToDouble(data, offset);
                offset += 8;
            }

            return offset;
        }

        public override string ToString()
        {
            return "MFloatArray: " +
            "\ncol: " + System.String.Join(", ", col.ToList());
        }
    }
}
