//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MissionManagement
{
    public class MPlotControl : Message
    {
        public const string RosMessageName = "mission_management/PlotControl";

        //  True if the car should drive
        public bool car;
        //  True if slam is activated
        public bool slam;

        public MPlotControl()
        {
            this.car = false;
            this.slam = false;
        }

        public MPlotControl(bool car, bool slam)
        {
            this.car = car;
            this.slam = slam;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.car));
            listOfSerializations.Add(BitConverter.GetBytes(this.slam));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.car = BitConverter.ToBoolean(data, offset);
            offset += 1;
            this.slam = BitConverter.ToBoolean(data, offset);
            offset += 1;

            return offset;
        }

        public override string ToString()
        {
            return "MPlotControl: " +
            "\ncar: " + car.ToString() +
            "\nslam: " + slam.ToString();
        }
    }
}
